
version: "3"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: wikipublic
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs123
    volumes:
      - db-wiki-public:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:2
    restart: always
    ports:
      - "3003:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs123
      DB_NAME: wikipublic
    depends_on:
      - db
    volumes:
      - wiki-public-data:/wiki/data

volumes:
  db-wiki-public:
  wiki-public-data:
