
name: Deploy Wiki.js Sites

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/opt/wikijs-deploy"

      - name: Restart services via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/wikijs-deploy/instances/wiki1 && docker-compose down && docker-compose up -d
            cd /opt/wikijs-deploy/instances/wiki2 && docker-compose down && docker-compose up -d
            cd /opt/wikijs-deploy/instances/wiki-public && docker-compose down && docker-compose up -d
            sudo systemctl reload nginx
